### ISSUE TITLE
Regex in function throws error

### ISSUE THREAD

**Issue by creatorrr** [firebase/blaze_compiler#17]
```
functions:
 - isEmail(str): str.match(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,14}$/i) != null
```

throws error during compilation with message `Error: Bug: 4 Unexpected situation in type system rule`.

Is this as expected? Does blaze not support regular expressions in functions?

**Comment by sarahwiley** [comment]
@tomlarkworthy @creatorrr Were you able to get regex working? I thought I just had mal-formed regex but now I have stripped everything out of my file but one regex call and am still getting the error "Bug: 4 Unexpected situation in type system on 'rule' " on compile. I am totally sure I could be doing something wrong but if you have any pointers I'd appreciate it. Here is my input file:

`schema:
  properties:
    comment:
      type: string
      constraint: next.matches(/abc/)

access:
  - location: comment/
    read: true
    write: true`

**Comment by tomlarkworthy** [comment]
Close to getting the formatting Sarah :) Use three backticks, not just one, either side of the code. Use "preview" to see if your formatting worked or not before sending.

Sorry creatorr,  I missed your reply in October. 

Yeah, so Sarah, so for obscure reasons string methods don't work on prev and next. Try:

next.val().matches(/abc/)

I am gonna update the compiler warning for this case as it trips everyone up

**Comment by sarahwiley** [comment]
I'll get the formatting next time :) @tomlarkworthy 
Thanks so much for your quick reply!
That did the trick. Sorry to bother.
Thanks,
Sarah
