### ISSUE TITLE
Nested functions causing strange text replacement error

### ISSUE THREAD

**Issue by chrishowes** [firebase/blaze_compiler#28]
I have two functions: 

```
  - isUser(uid): root.authUserIndex[auth.userid] === uid || isShopper()
  - isShopper(): root.users[root.authUserIndex[auth.uid]].isShopper === true
```

along with the following rule:
```
   - location: "/users/$userid/"
    read: isUser($userid)
    write: isUser($userid)
```

it LOOKS like that the isShopper() function is getting replaced into the isUser(uid) function, and since uid is a parameter in the first function, the resulting rule comes out to be:
```  

".read":"false||false||root.child('authUserIndex').child(auth.$userid).val()===$userid||root.child('users').child(root.child('authUserIndex').child(auth.$userid).val()).child('isShopper').val()===true"

```
(notice the auth.$userid part). I believe this is a bug, and the obvious workaround is to rename my variables (which I did), but just wanted to make you guys aware of a potential issue here.

**Comment by tomlarkworthy** [comment]
scoping on function params is still a bit weird but this particular issue is now resolved in 0.0.26
