### ISSUE TITLE
Constraint with child() method produces compilation error

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#34]
I have isolated the problem to the following constraint:

    constraint: (!prev.parent().child('registrationDate').exists())

I get a `Bug: 4 Unexpected situation in type system rule` error when trying to compile the rules.

If I remove the `child()` method the compilation passes:

    constraint: (!prev.parent().exists())

Is there something I don't understand or is this actually a bug?

**Comment by nnyman** [comment]
Possibly related: the rule `prev.parent()['registrationDate']` passes the compilation, but the compiler outputs `data.child('registrationDate')` effectively ignoring the `parent()` method.

**Comment by tomlarkworthy** [comment]
Hi, the .child syntax isn't supported. There are two forms you could use in blaze:-
1. (!prev.parent().registrationDate.exists())     
or
2. (!prev.parent()['registrationDate'].exists())   (useful form if the child value is computed)

In my tests the parent is not ignored, if you send me the full rules I can try to replicate, email me at larkworthy@google.com if they are private.

Thanks for reporting, I'll add a specific error for trying to use .child as I expect it's a common gotcha.

**Comment by nnyman** [comment]
Hi, yes it would be good to mention in the docs that .child isn't supported, and also that the first form `prev.parent().registrationDate` *is* supported. For some reason I assumed I cannot use functions like parent() within the dot notation. Now that I think of it, I don't know why. :)
