### ISSUE TITLE
Redirects and rewrites

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#35]
Hi, do you have any plans to support redirects, rewrites and custom headers in blaze compiler?

**Comment by tomlarkworthy** [comment]
no, Blaze is a layer over the existing security rules and they do not support that kind of functionality.

**Comment by nnyman** [comment]
Sorry, my bad. For some reason I was thinking rewrites are defined in the
rules json, although the docs clearly say they are defined in firebase.json.
