### ISSUE TITLE
Can't have multiple multi-line examples 

### ISSUE THREAD

**Issue by sarahwiley** [firebase/blaze_compiler#39]
The first multi-line example is fine, but as soon as a second multi-line example is added then there seems to be a parse error. If I collapse the first multi-line example into a single line, then they both work as expected.

Here is the input for the examples I'm trying to run:
examples:
 - {externalUsers : {
    "facebook:10152415019676650" : 7,
    "facebook:10152713523692632" : 8
    }}
  - {usersToMerge: {
      {"werwer": 8},
      {"xcvxcv": 9},
      {"rtyrty": 1}
     }}

Here is the output from the error case (two multi-line examples):

Sarahs-MacBook-Pro:beehive sarahwiley1$ blaze rules.yaml
transpiling rules.yaml
error line 7:14
{ authorLookup: 
   { type: 'object',
     properties: { publisher: [Object] },
     examples: [ {} ] },
  blacklist: { '$id': { type: 'string' } },
  comments: 
   { type: 'object',
     indexOn: [ 'pageGuid', 'createdBy', 'processed', 'authorUserId' ],
     '$commentId': 
      { type: 'object',
        properties: [Object],
        additionalProperties: false } },
  currentUserId: { type: 'number', constraint: 'next === prev+1' },
  externalUsers: { type: 'object', '$externalUserId': { type: 'number' } },
  newComments: 
   { type: 'object',
     '$commentId': 
      { type: 'object',
        required: [Object],
        constraint: '((  next.hasChild(\'rating\') && root[\'comments\'][next[\'replyToCommentId\']][\'createdBy\'] !== next[\'createdBy\'] ) || !next[\'rating\'].exists() ) && ( (!next.hasChild(\'createdBy\') && next.hasChildren([\'authorId\', \'permalink\'])) || (next[\'createdBy\'] === root[\'externalUsers\'][auth.uid] && next[\'replyToCommentId\'].exists()) ) && (next[\'rating\'].exists() || next[\'content\'].exists())',
        properties: [Object],
        additionalProperties: false } },
  users: 
   { type: 'object',
     indexOn: 'processed',
     '$userId': 
      { type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false } },
  usersToMerge: { type: 'object', '$externalUserId': { type: 'number' } },
  settings: { type: 'object' } }
cannot validate blaze file with blaze schema
data was on path: /schema/properties
the schema constraint was defined at 
Unknown property (not in schema)
run with -v option for fuller error messages

**Comment by sarahwiley** [comment]
Ha looks like in my sample above, the multiple lines were collapsed into a single line for each of the two supplied examples when I submitted this issue. Just add a few carriage returns and tabs in there to replicate.

**Comment by tomlarkworthy** [comment]
Thanks for reporting, I'll have a look.

**Comment by tomlarkworthy** [comment]
OK I am not completely sure where the problem is. The following constructs are all valid, but I am not sure I am expressing what you intend:

```
    examples:
      - externalUsers : { "facebook:10152415019676650" : 7, "facebook:10152713523692632" : 8 }
      - usersToMerge: {{"werwer": 8}, {"xcvxcv": 9}, {"rtyrty": 1} }
      - externalUsers:
        facebook:10152415019676650 : {7}
        facebook:10152713523692632 : {8}
      - externalUsers:
        facebook:10152415019676650 :
          7
        facebook:10152713523692632 :
          8
      - usersToMerge:
        werwer: 8
        xcvxcv: 9
        rtyrty: 1
      - {{externalUsers : { "facebook:10152415019676650" : 7, "facebook:10152713523692632" : 8 }},
        {usersToMerge: { {"werwer": 8}, {"xcvxcv": 9}, {"rtyrty": 1} }}}
```

You can use triple backticks \` (below ESC on my keyboard, NOTE: \` is not the same single or double quotes i.e. " or ') to enclose a block of literal code. My guess is that you are not fully expressing yourself in proper YAML, so maybe take a look at http://docs.ansible.com/YAMLSyntax.html

examples is a list of dictionaries. Because classic YAML dictionaries require lots of newlines, I tend to encode the elements inline using JSON {}, (they call this "abbreviated form" in the above link). Anyway post me the example again if you can;t figure it out, use backticks.
