### ISSUE TITLE
Maybe less logging by default?

### ISSUE THREAD

**Issue by jyasskin** [firebase/blaze_compiler#41]
```
$ cat rules.yaml
schema:
  type: object
  additionalProperties: false
  properties:
    foo:
      type: string
$ blaze rules.yaml|&wc -l
1407
```

1407 lines of output seems excessive for a compiler that isn't even reporting errors.

**Comment by tomlarkworthy** [comment]
Whoops! I forgot to turn of a development flag last npm publish. Fixed! Thanks for letting me know
