### ISSUE TITLE
additionalProperties value not being inherited from definitions. 

### ISSUE THREAD

**Issue by skoczen** [firebase/blaze_compiler#42]
Hey there,

Full disclosure: I'm trying to get my first big project spec'd out in blaze, so it's definitely possible I'm doing this wrong.  However, I'm not seeing `additionalProperties` be passed down from a definition.

Here's a stripped down rules.yml to illustrate

```yml
schema:
    definitions:
        user:
            type: object
            additionalProperties: false
            properties:
                first_name: {type: string}

    type: object
    properties:
        users: 
            type: object
            additionalProperties: false
            $userid: 
                type: object
                additionalProperties: false
                properties:
                    profile: {$ref: "#/definitions/user" }

            examples:
                - {"123": {"profile": {first_name: "Sally"}}}
            nonexamples:
                - {"123": {"profile": {first_name: "Sally", "bonus_data": "some"}}}


access:
    -   location:   "/"
        read:       true
        write:      false
```

I'd expect this to pass, but instead, I get:

```bash
error line 23:19
{ '123': { profile: { first_name: 'Sally', bonus_data: 'some' } } }
nonexample erroneously passed
```

Do I have this formatted incorrectly / have wrong assumptions?  Or is there a bug lurking?

Many thanks!

**Comment by tomlarkworthy** [comment]
Yeah I have replicated. I will look into it, thanks for reporting!

**Comment by tomlarkworthy** [comment]
OK fixed for 0.0.28, was trickier than expected, it was that the definition was not visible to the non-example runner. As the absence of type information makes the node just general JSON, the profile element became untyped and accepts anything (imagine replacing the {$ref} with just {})

Annoying bug, thanks a lot of finding it. If its any consolation to generated code was fine, it was just the test runner whose environment was not setup properly with respect to $ref variables.

**Comment by skoczen** [comment]
Great, thanks for the quick turnaround - will install in the AM and give it a go!

**Comment by skoczen** [comment]
Working great - thanks again!
