### ISSUE TITLE
Error: Cannot find module 'blaze_compiler'

### ISSUE THREAD

**Issue by pho3nixf1re** [firebase/blaze_compiler#45]
While attempting to load from a node test suite, I found that blaze could not be imported. The reason is that the 'main' file is `blaze.js` but that file does not exist. Instead, the 'main' file should be `src/blaze.js`.

**Comment by pho3nixf1re** [comment]
Actually, I had to manually include the `src/compile` file for it to work as a compilation API.

**Comment by tomlarkworthy** [comment]
Could you send me a PR?
