### ISSUE TITLE
Nested objects write permission is missing

### ISSUE THREAD

**Issue by mutovkin** [firebase/blaze_compiler#46]
I've moved the rules in Firechat application to Yaml file in order to allow me to modify schema easier, the minimal is below.

    functions:
      - isAuth():                   auth != null
      - isServer():                 auth.uid === "publisher"
      - isModerator():              root.moderators.hasChild(auth.uid) === true
      - isRoomPublic():             root['room-metadata'].$roomId.type !== 'private'
      - isRoomAuthorized():         root['room-metadata'].$roomId.autorizedUsers.hasChild(auth.uid) === true
      - canReadRoomMsgs():          isRoomPublic() || isRoomAuthorized()
      - canWriteMessage():          isAuth() && ( prev === null || isModerator() ) && (isRoomPublic() || isRoomAuthorized())

    schema:
      type: object
      properties:
        #Conference is a collection of rooms
        room-messages:
          type: object
          properties:
            $roomId:
              type: object
              properties:
                $msgId:
                  type: object
                  properties:
                    userId:     {type: string}
                    name:       {type: string}
                    message:    {type: string}
                    timestamp:  {type: number}
                    #Per message list of users who read it
                    readBy:
                      type: object
                      properties:
                        $userId: {type: boolean}
                  required: [userId, name, message, timestamp]
        moderators: {}

    access:
      #Root by default nothing to read or write
      - location: /
        write: false
        read: false

      #Messages deposited into each of the rooms
      - location: room-messages/$roomId/
        read: canReadRoomMsgs()
      - location: room-messages/$roomId/$msgId
        write: canWriteMessage()

      #Misc structures
      - location: moderators/
        read:   isAuth()
        write:  isServer()

Here is something unexpected that I'm seeing after compilation with blaze:

    {
      "rules":{
        ".write":"(((false)))",
        ".read":"false",
        "room-messages": {
          ".write":"((false))",
          ".read":"false",
          "$roomId": {
            ".write":"((false))",
            ".read":"((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))",
            "$msgId": {
              ".write":"((((false))))",
              ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
              "userId": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "name": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "message": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "timestamp": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isNumber())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "readBy": {
                ".write":"(false)",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
                "$userId": {
                  ".write":"((((newData.parent().parent().val()==null||newData.parent().parent().child('userId').exists()&&newData.parent().parent().child('name').exists()&&newData.parent().parent().child('message').exists()&&newData.parent().parent().child('timestamp').exists())&&(!newData.exists()||newData.isBoolean())&&auth!=null&&(data.parent().parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                  ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
                }
              }
            }
          }
        },
        "moderators": {
          ".write":"(((auth.uid==='publisher')))",
          ".read":"((auth!=null))"
        }
      }
    }

The specific part is:

      "$roomId": {
        ".write":"((false))",

This does not let me write any new rooms even as "moderator".
I'm noticing that whenever I have nested wildchild schema I get write to be permanently false for the root child but not the leaf nodes. Still Firebase prevents writing such structures.

**Comment by tomlarkworthy** [comment]
Try using a wilderchild ~$ instead of $

On 15 Jul 2015 9:21 am, "Serguei Moutovkin" <notifications@github.com>
wrote:
>
> I've moved the rules in Firechat application to Yaml file in order to
allow me to modify schema easier, the minimal is below.
>
> functions:
>   - isAuth():                   auth != null
>   - isServer():                 auth.uid === "publisher"
>   - isModerator():              root.moderators.hasChild(auth.uid) ===
true
>   - isRoomPublic():             root['room-metadata'].$roomId.type !==
'private'
>   - isRoomAuthorized():
root['room-metadata'].$roomId.autorizedUsers.hasChild(auth.uid) === true
>   - canReadRoomMsgs():          isRoomPublic() || isRoomAuthorized()
>   - canWriteMessage():          isAuth() && ( prev === null ||
isModerator() ) && (isRoomPublic() || isRoomAuthorized())
>
> schema:
>   type: object
>   properties:
>     #Conference is a collection of rooms
>     room-messages:
>       type: object
>       properties:
>         $roomId:
>           type: object
>           properties:
>             $msgId:
>               type: object
>               properties:
>                 userId:     {type: string}
>                 name:       {type: string}
>                 message:    {type: string}
>                 timestamp:  {type: number}
>                 #Per message list of users who read it
>                 readBy:
>                   type: object
>                   properties:
>                     $userId: {type: boolean}
>               required: [userId, name, message, timestamp]
>     moderators: {}
>
>
> access:
>   #Root by default nothing to read or write
>   - location: /
>     write: false
>     read: false
>
>   #Messages deposited into each of the rooms
>   - location: room-messages/$roomId/
>     read: canReadRoomMsgs()
>   - location: room-messages/$roomId/$msgId
>     write: canWriteMessage()
>
>   #Misc structures
>   - location: moderators/
>     read:   isAuth()
>     write:  isServer()
>
> Here is something unexpected that I'm seeing after compilation with blaze:
>
> {
>   "rules":{
>     ".write":"(((false)))",
>     ".read":"false",
>     "room-messages": {
>       ".write":"((false))",
>       ".read":"false",
>       "$roomId": {
>         ".write":"((false))",
>
".read":"((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))",
>         "$msgId": {
>           ".write":"((((false))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
>           "userId": {
>
".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
>           },
>           "name": {
>
".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
>           },
>           "message": {
>
".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
>           },
>           "timestamp": {
>
".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isNumber())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
>           },
>           "readBy": {
>             ".write":"(false)",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
>             "$userId": {
>
".write":"((((newData.parent().parent().val()==null||newData.parent().parent().child('userId').exists()&&newData.parent().parent().child('name').exists()&&newData.parent().parent().child('message').exists()&&newData.parent().parent().child('timestamp').exists())&&(!newData.exists()||newData.isBoolean())&&auth!=null&&(data.parent().parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
>
".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
>             }
>           }
>         }
>       }
>     },
>     "moderators": {
>       ".write":"(((auth.uid==='publisher')))",
>       ".read":"((auth!=null))"
>     }
>   }
> }
>
> The specific part is:
>
>   "$roomId": {
>     ".write":"((false))",
>
> This does not let me write any new rooms even as "moderator".
> I'm noticing that whenever I have nested wildchild schema I get write to
be permanently false for the root child but not the leaf nodes. Still
Firebase prevents writing such structures.

**Comment by mutovkin** [comment]
Unfortunately this didn't help. 

Input:

    functions:
      - isAuth():                   auth != null
      - isServer():                 auth.uid === "publisher"
      - isModerator():              root.moderators.hasChild(auth.uid) === true
      - isRoomPublic():             root['room-metadata'].$roomId.type !== 'private'
      - isRoomAuthorized():         root['room-metadata'].$roomId.autorizedUsers.hasChild(auth.uid) === true
      - canReadRoomMsgs():          isRoomPublic() || isRoomAuthorized()
      - canWriteMessage():          isAuth() && ( prev === null || isModerator() ) && (isRoomPublic() || isRoomAuthorized())

    schema:
      type: object
      properties:
        #Conference is a collection of rooms
        room-messages:
          type: object
          properties:
            ~$roomId:
              type: object
              properties:
                ~$msgId:
                  type: object
                  properties:
                    userId:     {type: string}
                    name:       {type: string}
                    message:    {type: string}
                    timestamp:  {type: number}
                    #Per message list of users who read it
                    readBy:
                      type: object
                      properties:
                        ~$userId: {type: boolean}
                  required: [userId, name, message, timestamp]
        moderators: {}


    access:
      #Root by default nothing to read or write
      - location: /
        write: false
        read: false

      #Messages deposited into each of the rooms
      - location: room-messages/$roomId/
        read: canReadRoomMsgs()
      - location: room-messages/$roomId/$msgId
        write: canWriteMessage()

      #Misc structures
      - location: moderators/
        read:   isAuth()
        write:  isServer()

Output:

    {
      "rules":{
        ".write":"(false)",
        ".read":"false",
        "room-messages": {
          ".write":"(false)",
          ".read":"false",
          "$roomId": {
            ".write":"(false)",
            ".validate":"(false)",
            ".read":"((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))",
            "$msgId": {
              ".write":"((((!newData.exists()||newData.hasChildren())&&(newData.val()==null||newData.child('userId').exists()&&newData.child('name').exists()&&newData.child('message').exists()&&newData.child('timestamp').exists())&&(!newData.child('userId').exists()||newData.child('userId').isString())&&(!newData.child('name').exists()||newData.child('name').isString())&&(!newData.child('message').exists()||newData.child('message').isString())&&(!newData.child('timestamp').exists()||newData.child('timestamp').isNumber())&&(!newData.child('readBy').exists()||newData.child('readBy').hasChildren())&&auth!=null&&(data.val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
              ".validate":"((((!newData.exists()||newData.hasChildren())&&(newData.val()==null||newData.child('userId').exists()&&newData.child('name').exists()&&newData.child('message').exists()&&newData.child('timestamp').exists())&&(!newData.child('userId').exists()||newData.child('userId').isString())&&(!newData.child('name').exists()||newData.child('name').isString())&&(!newData.child('message').exists()||newData.child('message').isString())&&(!newData.child('timestamp').exists()||newData.child('timestamp').isNumber())&&(!newData.child('readBy').exists()||newData.child('readBy').hasChildren())&&auth!=null&&(data.val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
              ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
              "userId": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "name": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "message": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isString())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "timestamp": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.isNumber())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
              },
              "readBy": {
                ".write":"((((newData.parent().val()==null||newData.parent().child('userId').exists()&&newData.parent().child('name').exists()&&newData.parent().child('message').exists()&&newData.parent().child('timestamp').exists())&&(!newData.exists()||newData.hasChildren())&&auth!=null&&(data.parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))",
                "$userId": {
                  ".write":"((((newData.parent().parent().val()==null||newData.parent().parent().child('userId').exists()&&newData.parent().parent().child('name').exists()&&newData.parent().parent().child('message').exists()&&newData.parent().parent().child('timestamp').exists())&&(!newData.exists()||newData.isBoolean())&&auth!=null&&(data.parent().parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                  ".validate":"((((newData.parent().parent().val()==null||newData.parent().parent().child('userId').exists()&&newData.parent().parent().child('name').exists()&&newData.parent().parent().child('message').exists()&&newData.parent().parent().child('timestamp').exists())&&(!newData.exists()||newData.isBoolean())&&auth!=null&&(data.parent().parent().val()===null||root.child('moderators').hasChild(auth.uid)===true)&&(root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true))))",
                  ".read":"(((root.child('room-metadata').child($roomId).child('type').val()!=='private'||root.child('room-metadata').child($roomId).child('autorizedUsers').hasChild(auth.uid)===true)))"
                }
              }
            }
          }
        },
        "moderators": {
          ".write":"(((auth.uid==='publisher')))",
          ".read":"((auth!=null))"
        }
      }
    }

**Comment by mutovkin** [comment]
I was wrong with my previous comment. At root level I've preserved false permission. ~$ (wilderchild) solves the issue.
