### ISSUE TITLE
cannot be cast from JString to JObject

### ISSUE THREAD

**Issue by nicholasf** [firebase/blaze_compiler#53]
Hi,

Based on the regex example at  https://www.firebase.com/docs/security/guide/securing-data.html#section-validate I'm trying to specify a regex constraint:

```
          mobile: {type: string}
          constraint: (newData.isString() && newData.val().matches(/^\+(?:[0-9] ?){6,14}[0-9]$/)) #E123 https://en.wikipedia.org/wiki/E.123

```

Transpiling results in:

```
annotate_schema (newData.isString() && newData.val().matches(/^\+(?:[0-9] ?){6,14}[0-9]$/))
Error: Type error

cannot be cast from JString to JObject
    at JString.JValue.castError (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:142:26)
    at JString.JValue.cast (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:149:24)
    at JString.JValue.asObject (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:163:30)
    at getWildchild (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:562:10)
    at annotate_schema (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:305:9)
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:298:53
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:329:13
    at Dictionary.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/util/Collections.ts:891:27)
    at JObject.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:328:25)
    at annotate_schema (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:296:54)

```

Am I able to embed this kind of regex into rules.yaml? 

Cheers,
Nicholas

**Comment by tomlarkworthy** [comment]
Should be able to. I'll try it out tomorrow.

Hi,

Based on the regex example at
https://www.firebase.com/docs/security/guide/securing-data.html#section-validate
I'm trying to specify a regex constraint:

          mobile: {type: string}
          constraint: (newData.isString() &&
newData.val().matches(/^\+(?:[0-9] ?){6,14}[0-9]$/)) #E123
https://en.wikipedia.org/wiki/E.123

Transpiling results in:

annotate_schema (newData.isString() &&
newData.val().matches(/^\+(?:[0-9] ?){6,14}[0-9]$/))
Error: Type error

cannot be cast from JString to JObject
    at JString.JValue.castError
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:142:26)
    at JString.JValue.cast
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:149:24)
    at JString.JValue.asObject
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:163:30)
    at getWildchild
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:562:10)
    at annotate_schema
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:305:9)
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:298:53
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:329:13
    at Dictionary.forEach
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/util/Collections.ts:891:27)
    at JObject.forEach
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:328:25)
    at annotate_schema
(/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:296:54)


Am I able to embed this kind of regex into rules.yaml?

Cheers,
Nicholas

—
Reply to this email directly or view it on GitHub
<https://github.com/firebase/blaze_compiler/issues/53>.

**Comment by nicholasf** [comment]
Terrific. We're really keen to keep blaze_compiler as the start of our toolchain for rules.json.

**Comment by tomlarkworthy** [comment]
The following schema works for me
```
source:
  schema:
    constraint: (newData.isString() && newData.val().matches(/^\+(?:[0-9] ?){6,14}[0-9]$/))
  access:
    - location: /
      write: true
```

making me think the error is outside of the regex, can you email me the full rules, you can use larkworthy on the google.com domain.

**Comment by nicholasf** [comment]
Thanks. I'm still getting the error. Will email you now.
