### ISSUE TITLE
Unexpected implementation level of access rules.

### ISSUE THREAD

**Issue by dewetburger** [firebase/blaze_compiler#56]
I have the following yaml rules:

```
schema:

  type: object
  additionalProperties: false
  properties:
    test:
      type: object
      properties:
        $parentId:
          type: object
          properties:
            $childId:
              type: object
              properties:
                timestamp: {type: number}

access:
  - location: /test/$parentId
    read:     auth.uid != null
    write:    auth.uid != null && prev.exists() == false

  - location: /test/$parentId/$childId
    write:    auth.uid != null && (prev.timestamp.exists() == false || next.timestamp >= prev.timestamp)
```

which generates the following rules.json file:

```
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "test": {
      ".write":"false",
      ".read":"false",
      "$parentId": {
        ".write":"false",
        ".read":"(auth.uid!=null)",
        "$childId": {
          ".write":"((((auth.uid!=null&&data.parent().exists()==false||auth.uid!=null&&(data.child('timestamp').exists()==false||newData.child('timestamp').val()>=data.child('timestamp').val())))))",
          ".read":"((auth.uid!=null))"
        }
      }
    },
    "$other":{".validate":"false"}
  }
}
```

The write rule in `- location: /test/$parentId` is implemented at the `$childId` level in the rules.json file, instead of the `$parentId` level. This causes a post to `\test\$parentId` to fail, which is not the intended behaviour.

**Comment by ginovva320** [comment]
The rules cascading in that manner is intended. I believe to unlock the $parentId for writes, you'd need to use a [$wilderchild](https://github.com/firebase/blaze_compiler#wilderchild). #46 is related.

**Comment by tomlarkworthy** [comment]
Wilderchild will fix one issue but there is another bug I noticed last week
you are hitting. I will fix that today.

The rules cascading in that manner is intended. I believe to unlock the
$parentId for writes, you'd need to use a $wilderchild
<https://github.com/firebase/blaze_compiler#wilderchild>. #46
<https://github.com/firebase/blaze_compiler/issues/46> is related.

—
Reply to this email directly or view it on GitHub
<https://github.com/firebase/blaze_compiler/issues/56#issuecomment-133045112>
.

**Comment by tomlarkworthy** [comment]
OK the bug I thought existed didn't. So 
1. you need a wilderchild's on $childId to do nesting, as ginovva320 said, so ~$childId
2. wilderchilds are not properties, they are their own special commands so do not appear in the properties field. I have added some special error messages for detecting that case, as you are not the first to hit that unexpected behavior. (FYI it's to do with the JSONSchema spec)

Putting it all together I think this is what you want:-

```
schema:
  type: object
  additionalProperties: false
  properties:
    test:
      type: object
      $parentId:
        type: object
        ~$childId:
          type: object
          properties:
            timestamp: {type: number}

access:
  - location: /test/$parentId
    read:     auth.uid != null
    write:    auth.uid != null && prev.exists() == false

  - location: /test/$parentId/$childId
    write:    auth.uid != null && (prev.timestamp.exists() == false || next.timestamp >= prev.timestamp)
```

the better error message is in version 0.0.34
