### ISSUE TITLE
After updating to version 0.0.35, blaze compile never finishes

### ISSUE THREAD

**Issue by phyamane** [firebase/blaze_compiler#62]
Version 0.0.34 and earlier still work without issue.

**Comment by tomlarkworthy** [comment]
thanks, I will investigate

**Comment by tomlarkworthy** [comment]
can you send me the file used to reproduce? send it to larkworthy@google.com

**Comment by phyamane** [comment]
Yes, just sent

On Fri, Sep 25, 2015 at 11:15 AM, Tom Larkworthy <notifications@github.com>
wrote:

> can you send me the file used to reproduce? send it to
> larkworthy@google.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/blaze_compiler/issues/62#issuecomment-143312294>
> .
>



-- 
*Patrick Yamane* *| Software Engineer*
Stack Labs | 10054 Pasadena Ave, Cupertino, CA 95014
m 251.751.6579 | e patrick@stacklighting.com

This electronic mail transmission may contain private, confidential and
privileged information that is for the sole use of the intended recipient.
If you are not the intended recipient, you are hereby notified that any
review, dissemination, distribution, archiving, or copying of this
communication
is strictly prohibited.  If you received this communication in error,
please reply to this message immediately and delete the original message
and the associated reply.

**Comment by tomlarkworthy** [comment]
Thanks for the report, perf regression fixed in 0.0.36
