### ISSUE TITLE
Support for Firebase rule string methods (toUpperCase, toLowerCase, etc)

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/blaze_compiler#63]
I couldn't find documentation of support of the standard Firebase rule string methods (defined in the [Firebase Rules API](https://www.firebase.com/docs/security/api/)). Are these available in Blaze and would they be used just as they would in the standard JSON rules (i.e. `next.toLowerString() === "some_lowercase_string"`)?

**Comment by mm-gmbd** [comment]
Also, is there a way to enforce a method, such as `toLowerString` in an `enum` constraint?

**Comment by tomlarkworthy** [comment]
Sorry for slow reply, I was on a leave of absense. Yes, the string methods are available. However, coercion to a string type is not availible, so you have to explicitly convert a datasnapshot to a value with .val().
```
next.val().toLowerCase()
```

**Comment by tomlarkworthy** [comment]
You can have a constraint alongside an enum. I am not sure that answers your 2nd question though
