### ISSUE TITLE
Regular Expression Issue for Email validation \ is getting repeated twice

### ISSUE THREAD

**Issue by ittechsathish** [firebase/blaze_compiler#65]
For Example:

github showing one \ after edit is done:

so, let me explain:
in regular expression escaped \ to double \ \

but blaze is changing them to \ \ \ \ .So to avoid this issue i am not escaping in blaze script.

Could you please confirm, can this be fixed.

/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}$/i

is changed to 

/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\\\.[A-Z]{2,4}$/i

**Comment by tomlarkworthy** [comment]
Sorry for delay I a have been on paternity leave, I will get to these
issues in the coming week.

**Comment by tomlarkworthy** [comment]
So the environment of Blaze is YAML, so you should expect some escaping from YAML.

Given: 
```
(newData.isString() && newData.val().matches(/\\./))
```
We expect YAML to take the `//` as a '/' when it gets to the regex. So we expect the regex to be:

```
/\./
```

Which is an escaped `.`, therefore only a literal `.` should be accepted by the regex. This is indeed the behavior I observe. What you are seeing is the YAML env escaping. You can turn this off by using single quotes! http://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml

So the following when enclosed in single quotes is not escaped
```
constraint: 'newData.val().matches(/\./)'
```

and the resultant expression is 

```
"((newData.val().matches(/\\./)))"
```
