### ISSUE TITLE
Functions calls doesn't evaluate the params before passing it 

### ISSUE THREAD

**Issue by Mohamed-Habshey** [firebase/blaze_compiler#67]
Hi Everyone,
Good Day

i had a situation in function i need to check if user is already member of class to be able to access this class data (video for ex.)

When passing param to function calls i expected to evaluate this param first before passing it to the function but i think you just pass the the param to the function and then evaluate it later.

Function:
- isClassMember(classid):  root.classes.classid.students.hasChild(auth.uid)

blaze rule:
 - location: /videos/$videoid/
    read:   isClassMember(prev.class)

**Expected generated rule:

 ".read":" root.child('classes')***.child(data.child('class').val())***.child('users').hasChild(auth.uid)"

as *prev.class* should be **data.child('class').val()**

**but i get:

  ".read":"root.child('classes')***.child(data.val()).child('class')***.child('users').hasChild(auth.uid)"

any ideas?? will be appreciated. :smile: 

Thanks in advance
Best Regards
M.H

**Comment by Mohamed-Habshey** [comment]
_**Anyone?**_

**Comment by tomlarkworthy** [comment]
I don't entirely understand what is going on internally. Its getting confused. This makes sure the expression is expanded in the right order:
```
isClassMember(classid): root.classes[classid].students.hasChild(auth.uid)
```

**Comment by Mohamed-Habshey** [comment]
@tomlarkworthy  thanks tom works great  :+1:  

really appreciate your help  

regards
M.H

**Comment by tomlarkworthy** [comment]
Sorry it took so long, you managed to time your post on the first day of a
2 week holiday for me.

**Comment by Mohamed-Habshey** [comment]
@tomlarkworthy  hhhhhhhahhahahhhh perfect timing :smile:  
thank you very much i really appreciate your help it helps me greatly.
